import java.time.Instant

plugins {
	id 'maven-publish'
	id 'fabric-loom' version '1.10-SNAPSHOT'
	id "me.shedaniel.unified-publishing" version "0.1.+"
}

ext.ENV = System.getenv()
def isLocal = !ENV.containsKey("GITHUB_RUN_NUMBER")

version = "${mod_version}-${isLocal ? "local.${Instant.now().epochSecond}" : "build.${ENV.GITHUB_RUN_NUMBER}"}"
group = project.maven_group
base.archivesName = project.archives_base_name

println("Building version: ${version}")

loom {
	interfaceInjection.enabled

	accessWidenerPath.set(file("src/main/resources/kubejs.accesswidener"))

	runs {
		client {
			client()

			if (ENV.MC_CLIENT_ARGS) {
				programArgs.addAll(ENV.MC_CLIENT_ARGS.split(' '))
			}

			vmArgs.addAll("-XX:+IgnoreUnrecognizedVMOptions", "-XX:+AllowEnhancedClassRedefinition")
			runDir = 'runs/client'
		}

		server {
			server()
			programArgs.add("--nogui")
			runDir = 'runs/server'
		}
	}
}

compileJava {
	options.encoding = "UTF-8"
	options.release.set(21)
	options.compilerArgs << '-parameters'
}

java {
	sourceCompatibility = targetCompatibility = JavaLanguageVersion.of(21)
	withSourcesJar()
}

repositories {
	mavenLocal()
	mavenCentral()

	maven {
		name = 'ParchmentMC'
		url = 'https://maven.parchmentmc.org'
		content {
			includeGroup "org.parchmentmc.data"
		}
	}

	maven {
		url "https://maven.latvian.dev/releases"
		content {
			includeGroup "dev.latvian.mods"
			includeGroup "dev.latvian.apps"
		}
	}

	maven {
		url "https://maven.architectury.dev/"
	}

	maven {
		url "https://maven.blamejared.com"
		content {
			includeGroup "mezz.jei"
			includeGroup "net.darkhax.bookshelf"
			includeGroup "net.darkhax.gamestages"
		}
	}

	maven {
		name = "TerraformersMC"
		url = "https://maven.terraformersmc.com/"
		content {
			includeGroup "dev.emi"
		}
	}

	maven {
		url 'https://jitpack.io'
		content {
			includeGroup "com.github.rtyley"
		}
	}

	maven { url = "https://mvn.devos.one/snapshots/" }
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.layered() {
		officialMojangMappings()
		parchment("org.parchmentmc.data:parchment-${project.parchment_mc_version}:${project.parchment_mapping_version}")
	}
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	modImplementation("teamreborn:energy:4.1.0")

	modApi("dev.latvian.mods:rhino:$rhino_version") { transitive(false) }

	modCompileOnly("dev.architectury:architectury-fabric:$architectury_version")
	modCompileOnly("mezz.jei:jei-1.21.1-fabric:$jei_version")
	modCompileOnly("me.shedaniel:RoughlyEnoughItems-fabric:$rei_version")
	modCompileOnly("dev.emi:emi-fabric:$emi_version:api")

	implementation("dev.latvian.apps:tiny-java-server:${project.tiny_server_version}")
	include("dev.latvian.apps:tiny-java-server:${project.tiny_server_version}")

	implementation("com.github.rtyley:animated-gif-lib-for-java:animated-gif-lib-${project.gif_lib_version}")
	include("com.github.rtyley:animated-gif-lib-for-java:animated-gif-lib-${project.gif_lib_version}")

	implementation("com.google.code.findbugs:jsr305:3.0.2")
}

processResources {
	def toReplace = [
			"version"      : project.version,
			"rhino_version": project.rhino_version,
	]

	println("[Process Resources] Replacing properties in resources: " + toReplace)

	inputs.properties toReplace
	filesMatching("fabric.mod.json") {
		expand toReplace
	}
}

jar {
	manifest {
		attributes([
				"Specification-Title"     : project.mod_id,
				"Specification-Vendor"    : project.mod_author,
				"Specification-Version"   : "1",
				"Implementation-Title"    : project.name,
				"Implementation-Version"  : version,
				"Implementation-Vendor"   : project.mod_author,
				"Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
		])
	}
}

publishing {
	publications {
		mavenNeoForge(MavenPublication) {
			artifactId = archives_base_name
			from components.java
		}
	}

	repositories {
		/*
		if (ENV.MAVEN_URL && ENV.MAVEN_USERNAME && ENV.MAVEN_TOKEN) {
			maven {
				url = ENV.MAVEN_URL
				credentials {
					username = ENV.MAVEN_USERNAME
					password = ENV.MAVEN_TOKEN
				}
			}
		}
		 */
	}
}

unifiedPublishing {
	project {
		releaseType = "${ENV.RELEASE_TYPE ?: 'release'}"
		gameVersions = Arrays.asList(project.supported_versions.split(', '))
		gameLoaders = ["fabric"]
		displayName = "$mod_name Fabric $project.version"
		//changelog = "https://kubejs.com/changelog?mc=${project.minecraft_version}"
		mainPublication jar

		relations {
			depends {
				curseforge = modrinth = "rhino"
			}
		}

		if (ENV.CURSEFORGE_KEY) {
			curseforge {
				token = ENV.CURSEFORGE_KEY
				id = project.curseforge_id
			}
		}

		if (ENV.MODRINTH_TOKEN) {
			modrinth {
				token = ENV.MODRINTH_TOKEN
				id = project.modrinth_id
				version = "$project.version+$project.name"
			}
		}
	}
}

afterEvaluate {
	tasks.withType(JavaCompile) {
		options.compilerArgs << "-Xmaxerrs" << "1000"
	}
}